name: Build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        system:
        - name: RaspiOS Lite 32 Bit, 11 (Bullseye), Pi 4b
          cpu: cortex-a7
          base_image: https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2023-05-03/2023-05-03-raspios-bullseye-armhf-lite.img.xz
          cpu_info: cpuinfo/raspberrypi_4b
    
    name: ${{ matrix.system.name }}
    
    steps:
    - uses: pguyot/arm-runner-action@v2
      with:
        base_image: ${{ matrix.system.base_image }}
        cpu: ${{ matrix.system.cpu }}
        cpu_info: ${{ matrix.system.cpu_info }}
        commands: |
            lscpu
            lsb_release -a
            apt-get update
            apt-get install -y \
              curl \
              ca-certificates \
              fontconfig \
              autoconf \
              file \
              g++ \
              gcc \
              libcups2-dev \
              libfontconfig1-dev \
              libasound2-dev \
              libx11-dev \
              libxext-dev \
              libxrender-dev \
              libxrandr-dev \
              libxtst-dev \
              libxt-dev \
              make \
              unzip \
              zip
              