name: Build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        system:
        - cpu: cortex-a7
          base_image: raspbian_lite:latest
          cpu_info: cpuinfo/raspberrypi_4b
    steps:
    - uses: pguyot/arm-runner-action@v2
      with:
        base_image: ${{ matrix.system.base_image }}
        cpu: ${{ matrix.system.cpu }}
        cpu_info: ${{ matrix.system.cpu_info }}
        commands: |
            lscpu